#!/bin/bash
# comp-star-rsem 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

#set -x
set +e
# diff returning 1 will exit script otherwise!!

main() {
    echo "Value of star_log: '$star_log'"
    echo "Value of star_bam: '$star_bam'"
    echo "Value of rsem_isoform_quant: '$rsem_isoform_quant'"
    echo "Value of rsem_gene_quant: '$rsem_gene_quant'"
    echo "Value of dataset: '$data_dir'"

    # The following line(s) use the dx command-line tool to download your file
    # inputs to the local file system using variable names for the filenames. To
    # recover the original filenames, you can use the output of "dx describe"
    # "$variable" --name".

    dx download "$star_log" -o star_log

    #dx download "$star_bam" -o star_bam

    #dx download "$rsem_isoform_quant" -o rsem_isoform_quant

    #dx download "$rsem_gene_quant" -o rsem_gene_quant

    dx download project-BKjyBz00ZZ0PZF5V7Gv00zqG:/test/"$data_dir"/*
    #dx download project-BKjyBz00ZZ0PZF5V7Gv00zqG:test/"$data_dir"/Log.final.out
    # Fill in your application code here.
    #
    # To report any recognized errors in the correct format in
    # $HOME/job_error.json and exit this script, you can use the
    # dx-jobutil-report-error utility as follows:
    #
    #   dx-jobutil-report-error "My error message"
    #
    # Note however that this entire bash script is executed with -e
    # when running in the cloud, so any line which returns a nonzero
    # exit code will prematurely exit the script; if no error was
    # reported in the job_error.json file, then the failure reason
    # will be AppInternalError with a generic error message.
    find

    echo Log.final.out
#    diff <(awk 'NR>4{print}' test/$data_dir/Log.final.out) <(awk 'NR>4{print}' star_log) > log_diff
    awk 'NR>4{print}' Log.final.out > a.log
    awk 'NR>4{print}' star_log > b.log

    echo `ls *log`

    diff a.log b.log > log_diff

    echo "Did the diff"
    log_diff=$(dx upload a.log --brief)
    dx-jobutil-add-output log_diff "$log_diff" --class=file
}
