#!/bin/bash

applet_dest='long-rna-seq-pipeline'
applets='merge-annotation prep-star prep-rsem prep-tophat concat-fastqs align-star-se align-star-pe align-tophat-pe align-tophat-se quant-rsem bam-to-bigwig-stranded bam-to-bigwig-unstranded'

project=$(dx find projects --name "$applet_dest")
if [ -z "$project" ]
  then
    dx new project "$applet_dest" --brief
fi

for applet in $applets; do
    echo "Building $applet at $applet_dest..."
    dx build "${applet}" --archive --destination "${applet_dest}:/"
done
